FROM maven:3-eclipse-temurin-17

ADD . /app/

ARG ASTRA_DB_ID=${ASTRA_DB_ID}
ARG ASTRA_DB_REGION=${ASTRA_DB_REGION}
ARG ASTRA_DB_APP_TOKEN=${ASTRA_DB_APP_TOKEN}
ARG ASTRA_DB_KEYSPACE=ecommerce
ARG ASTRA_STREAM_TENANT=${ASTRA_STREAM_TENANT}
ARG ASTRA_STREAM_URL=${ASTRA_STREAM_URL}
ARG ASTRA_STREAM_TOKEN=${ASTRA_STREAM_TOKEN}
ARG GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
ARG GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
#ARG ASTRA_SCB="scb_${ASTRA_DB_ID}_${ASTRA_DB_REGION}.zip"

# output Java version
RUN java -version

EXPOSE 8080

CMD mvn spring-boot:run -f /app/backend/pom.xml
